#pragma once

#include <functional>

/*
	One class for goto-definition and goto-references: identical flow
	(keybind -> caret position -> request -> shared picker), different LSP
	request and window title. Results live in LSPRequestState (thread-safe,
	stale-response guarded).
*/

#include "lsp_locations.h"
#include "lsp_request.h"
#include <vector>

// Generated by lspgen into <build>/lib/lsp-framework/generated (on include path).
#include "lsp/types.h"

class LSPClient;
class LspEditor;

class LSPGoto
{
  public:
	enum class Kind { Definition, References };

	LSPGoto(LSPClient &client, LspEditor &api, Kind kind);
	~LSPGoto();

	// Check keybind and trigger if conditions are met
	void get();

	// Render the picker UI
	void render();

	// True while a request is in flight (the picker shows "Searching…"
	// instead of "No results").
	bool isPending() const { return state.isPending(); }

	// UI-layer hook: renders results through the shared picker. Set by the
	// active backend view so the LSP core stays UI-free.
	std::function<void(
		const std::string &title, const std::vector<LSPLocation> &locations, bool &show)>
		resultRenderer;

	void setApi(LspEditor *editorApi) { api = editorApi; }

  private:
	Kind kind;
	bool show = false;
	LSPRequestState<std::vector<LSPLocation>> state;
	LSPClient *client = nullptr;
	LspEditor *api = nullptr;
};

// Jump within the document `api` currently shows: UTF-16 -> UTF-8 byte
// conversion against the DESTINATION line, then deferred center. Backends
// that must open another file first load it, then call this.
void lspJumpToLocation(LspEditor &api, const LSPLocation &location);
