/*
	lsp/lsp_includes.h

	Deliberate unity/aggregator header (PCH-style) for LSP translation units:
	pulls in the shared LSP/framework/editor includes every lsp/*.cpp needs so
	TUs compile against one stable include set. It must stay lean — no heavy
	or unrelated headers (in particular no <iostream>).
*/

#pragma once

// Generated by lspgen into <build>/lib/lsp-framework/generated (on include path).
#include "lsp/messages.h"
#include "lsp/types.h"

#include "../lib/lsp-framework/lsp/connection.h"
#include "../lib/lsp-framework/lsp/error.h"
#include "../lib/lsp-framework/lsp/messagehandler.h"
#include "../lib/lsp-framework/lsp/process.h"

#include "../editor/editor_api.h"
#include "../files/files.h"
#include "lsp_client.h"

#include <chrono>
#include <functional>
#include <future>
#include <map>
#include <memory>
#include <string>
#include <thread>
#include <vector>
