#pragma once

// Generated by lspgen into <build>/lib/lsp-framework/generated (on include path).
#include "lsp/messages.h"
#include "lsp/types.h"

#include "../lib/lsp-framework/lsp/connection.h"
#include "../lib/lsp-framework/lsp/error.h"
#include "../lib/lsp-framework/lsp/messagehandler.h"
#include "../lib/lsp-framework/lsp/process.h"

#include "../editor/editor_api.h"
#include "../files/files.h"
#include "lsp_client.h"

#include <chrono>
#include <functional>
#include <future>
#include <iostream>
#include <map>
#include <memory>
#include <string>
#include <thread>
#include <vector>
