#pragma once

#include "imgui.h"
#include <functional>
#include <future>
#include <map>
#include <memory>
#include <string>
#include <vector>

// Generated by lspgen into <build>/lib/lsp-framework/generated (on include path).
#include "lsp/types.h"

class EditorApi;
class FileExplorer;
class LSPClient;

class LSPGotoRef
{
  public:
	LSPGotoRef(LSPClient &client, EditorApi &api, FileExplorer &fileExplorer);
	~LSPGotoRef();

	// response data structure
	std::vector<std::map<std::string, std::string>> references;

	// Check keybind and trigger goto references if conditions are met
	void get();

	// Render the goto references UI
	void render();

	// Send LSP goto references request
	void
	request(int line,
			int character,
			std::function<void(const std::vector<std::map<std::string, std::string>> &)>
				callback);

	void setApi(EditorApi &editorApi) { api = &editorApi; }

  private:
	// Helper function to process the LSP response
	std::vector<std::map<std::string, std::string>>
	processResponse(const lsp::TextDocument_ReferencesResult &result);

	// Helper function to print structured results
	void printResponse(const std::vector<std::map<std::string, std::string>> &results);

	bool show;
	LSPClient *client = nullptr;
	EditorApi *api = nullptr;
	FileExplorer *fileExplorer = nullptr;

	// Async request handling
	bool pending;
	std::shared_ptr<std::future<void>> asyncResponse;
};
