#pragma once

/*
	One class for goto-definition and goto-references: identical flow
	(keybind -> caret position -> request -> shared picker), different LSP
	request and window title. Results live in LSPRequestState (thread-safe,
	stale-response guarded).
*/

#include "lsp_locations.h"
#include "lsp_request.h"
#include <vector>

// Generated by lspgen into <build>/lib/lsp-framework/generated (on include path).
#include "lsp/types.h"

class EditorApi;
class LSPClient;

class LSPGoto
{
  public:
	enum class Kind { Definition, References };

	LSPGoto(LSPClient &client, EditorApi &api, Kind kind);
	~LSPGoto();

	// Check keybind and trigger if conditions are met
	void get();

	// Render the picker UI
	void render();

	void setApi(EditorApi &editorApi) { api = &editorApi; }

  private:
	Kind kind;
	bool show = false;
	LSPRequestState<std::vector<LSPLocation>> state;
	LSPClient *client = nullptr;
	EditorApi *api = nullptr;
};
