#pragma once

#include <functional>

/*
	One class for goto-definition and goto-references: identical flow
	(keybind -> caret position -> request -> shared picker), different LSP
	request and window title. Results live in LSPRequestState (thread-safe,
	stale-response guarded).
*/

#include "lsp_locations.h"
#include "lsp_request.h"
#include <vector>

// Generated by lspgen into <build>/lib/lsp-framework/generated (on include path).
#include "lsp/types.h"

class LSPClient;
class LSPEditor;

// Picker-ownership arbitration: goto-definition and goto-references share one
// picker; while one result set is being rendered, a newly rendered set takes
// ownership and clears the previous owner's show flag so only one keeps
// rendering (two concurrent requests can not fight over the popup).
class LSPGotoArbiter
{
  public:
	void render(const std::function<void(const std::string &title,
										 const std::vector<LSPLocation> &locations,
										 bool &show)> &renderer,
				const std::string &title,
				const std::vector<LSPLocation> &locations,
				bool &show);

  private:
	bool *renderedShowFlag = nullptr; // last owner's show flag
};

class LSPGoto
{
  public:
	enum class Kind { Definition, References };

	LSPGoto(LSPClient &client, LSPEditor &api, Kind kind);
	~LSPGoto();

	// Check keybind and trigger if conditions are met
	void get();

	// Render the picker UI
	void render();

	// True while a request is in flight (the picker shows "Searching…"
	// instead of "No results").
	bool isPending() const { return state.isPending(); }

	// UI-layer hook: renders results through the shared picker. Set by the
	// active backend view so the LSP core stays UI-free.
	std::function<void(
		const std::string &title, const std::vector<LSPLocation> &locations, bool &show)>
		resultRenderer;

	void setApi(LSPEditor *editorApi) { api = editorApi; }

	// Route render() through the shared arbiter (both goto kinds share one
	// picker per client). Optional — without one, resultRenderer runs direct.
	void setArbiter(LSPGotoArbiter *a) { arbiter = a; }

  private:
	Kind kind;
	bool show = false;
	LSPRequestState<std::vector<LSPLocation>> state;
	LSPClient *client = nullptr;
	LSPEditor *api = nullptr;
	LSPGotoArbiter *arbiter = nullptr;
};

// Jump within the document `api` currently shows: UTF-16 -> UTF-8 byte
// conversion against the DESTINATION line, then deferred center. Backends
// that must open another file first load it, then call this.
void lspJumpToLocation(LSPEditor &api, const LSPLocation &location);
